# https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml

AllCops:
  TargetRubyVersion: 2.5.8
  Exclude:
    - 'docs/**'
    - 'db/schema.rb'
    - 'db/structure.sql'

Lint/AmbiguousOperator:
  Description: Checks for ambiguous operators in the first argument of a method invocation
    without parentheses.
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/ArrayAlignment:
  Description: Align the elements of an array literal if they span more than one line.
  Enabled: true
Layout/HashAlignment:
  Description: Align the elements of a hash literal if they span more than one line.
  Enabled: true
  EnforcedColonStyle: table
Layout/ParameterAlignment:
  Description: Align the parameters of a method call if they span more than one line.
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  Enabled: true
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause: 
  Enabled: false
Layout/LineLength:
  Description: Limit lines to 100 characters.
  Enabled: true
  Max: 100
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Description: Checks that exactly one space is used between a method name and the
    first argument for method calls without parentheses.
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Description: Checks that exactly one space is used between the arrow and the
    parenthesis in a lambda.
  Enabled: true
  EnforcedStyle: require_space
Lint/ParenthesesAsGroupedExpression:
  Description: Checks for method calls with a space before the opening parenthesis.
  Enabled: true
Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
Metrics/MethodLength:
  Enabled: true
  Max: 25
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/Alias:
  Description: Use alias_method instead of alias.
  Enabled: true
Style/ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  Enabled: false
Layout/ExtraSpacing:
  Description: Do not use unnecessary spacing.
  Enabled: true
Style/ParenthesesAroundCondition:
  Description: Don't use parentheses around the condition of an if/unless/while.
  Enabled: true
Style/PercentLiteralDelimiters:
  Description: Use `%`-literal delimiters consistently.
  Enabled: true
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%w': '()'
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: single_quotes
Style/TrailingCommaInHashLiteral:
  Description: Use a trailing comma in multi-line hashes.
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/TernaryParentheses:
  Enabled: false
Style/Documentation:
  Enabled: true
Style/MutableConstant:
  Enabled: true
