# https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'docs/**'
    - 'db/schema.rb'
    - 'db/structure.sql'

AbcSize:
  Enabled: false
AmbiguousOperator:
  Enabled: false
ExtraSpacing:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
MultilineMethodCallIndentation:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/StringLiterals:
  Enabled: false
